baseURL = "https://kgoto9.github.io/blog/"
publishDir = "docs"
languageCode = "ja"
title = "後藤のGo To BLOG"
logoHomeLink = "/blog"
theme = "hello-friend-ng"
canonifyurls = true

[[menu.main]]
  name = "Blog"
  url = "/blog/posts"
  weight = 1
